# Generated by Django 4.1.5 on 2023-02-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slashed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
